name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Safe Deploy to EC2
    runs-on: ubuntu-latest
    environment: EC2_HOST

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH with Safety
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Fail fast

            echo "🚀 Starting Safe Deployment..."

            # Define directories
            APP_DIR=/home/${USER}/backend-drf
            TMP_DIR=/home/${USER}/backend-drf_tmp

            echo "🧹 Cleaning any old tmp clone..."
            rm -rf $TMP_DIR

            echo "📥 Cloning fresh code to temp directory..."
            git clone https://${{ secrets.GH_TOKEN }}@github.com/mbrsagor/backend-drf.git $TMP_DIR

            cd $TMP_DIR
            git checkout develop
            git pull origin develop

            echo "🔨 Building Docker containers in temp dir..."
            docker-compose -f docker-compose.yml build --no-cache

            echo "✅ Running tests & migrations in temp dir..."
            chmod +x script.sh
            ./script.sh || {
              echo "❌ script.sh failed. Canceling deployment."; 
              exit 1;
            }

            echo "🧬 Stopping old app and swapping new version..."
            cd ~
            docker-compose -f $APP_DIR/docker-compose.yml down
            rm -rf $APP_DIR
            mv $TMP_DIR $APP_DIR

            echo "🚀 Starting new version..."
            cd $APP_DIR
            docker-compose up -d

            echo "✅ Deployment completed successfully and live app updated."
